[phases.setup]
nixPkgs = ["nodejs_22"]
aptPkgs = [
  "libcairo2-dev",
  "libpango1.0-dev",
  "libjpeg-dev",
  "libgif-dev",
  "librsvg2-dev",
  "pkg-config",
  "python3",
  "libfontconfig1-dev",
  "libfreetype6-dev"
]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]
